import {
  FuelType,
  PaymentStatus,
  ReservationStatus,
  TransmissionType,
  type DayHours,
  type OpeningHours,
  type PriceBreakdown,
  type ReservationExtra,
  type VehicleExtra,
  type VehicleFeature,
} from '../types';
import type {
  AdminCustomer,
  AdminOffice,
  AdminReservation,
  AdminUser,
  AdminVehicle,
  AdminVehicleGroup,
  AuditLog,
  Campaign,
  FeatureFlag,
  OccupancyReport,
  PopularVehicleReportItem,
  PricingRule,
  ReportStat,
  RevenueReport,
} from './types';

const weekdayHours: DayHours = { open: '08:00', close: '22:00', isClosed: false };
const weekendHours: DayHours = { open: '09:00', close: '21:00', isClosed: false };

const openingHours: OpeningHours = {
  monday: weekdayHours,
  tuesday: weekdayHours,
  wednesday: weekdayHours,
  thursday: weekdayHours,
  friday: weekdayHours,
  saturday: weekendHours,
  sunday: weekendHours,
};

const vehicleFeatures: Record<string, VehicleFeature> = {
  ac: { id: 'feature-ac', name: 'Klima', icon: 'snowflake' },
  auto: { id: 'feature-auto', name: 'Otomatik Vites', icon: 'gear' },
  bluetooth: { id: 'feature-bluetooth', name: 'Bluetooth', icon: 'bluetooth' },
  nav: { id: 'feature-nav', name: 'Navigasyon', icon: 'navigation-arrow' },
  camera: { id: 'feature-camera', name: 'Geri Görüş Kamerası', icon: 'camera' },
  hybrid: { id: 'feature-hybrid', name: 'Hibrit', icon: 'leaf' },
};

const vehicleExtras: VehicleExtra[] = [
  {
    id: 'extra-child-seat',
    name: 'Çocuk Koltuğu',
    description: '0-36 kg uyumlu çocuk koltuğu',
    dailyPrice: 12,
    maxQuantity: 2,
    icon: 'baby',
  },
  {
    id: 'extra-full-insurance',
    name: 'Tam Kasko',
    description: 'Muafiyetsiz kapsamlı koruma',
    dailyPrice: 25,
    maxQuantity: 1,
    icon: 'shield-check',
  },
  {
    id: 'extra-wifi',
    name: 'Araç İçi Wi-Fi',
    description: 'Sınırsız günlük veri paketi',
    dailyPrice: 9,
    maxQuantity: 1,
    icon: 'wifi-high',
  },
];

export const mockOffices: AdminOffice[] = [
  {
    id: 'office-gzp',
    name: 'Gazipaşa Airport',
    code: 'GZP',
    address: 'Gazipaşa Havalimanı İç Hatlar Geliş Terminali',
    city: 'Antalya',
    district: 'Gazipaşa',
    postalCode: '07900',
    phone: '+90 242 555 10 01',
    email: 'gzp@ayracar.com',
    coordinates: { latitude: 36.2993, longitude: 32.3014 },
    openingHours,
    type: 'airport',
    isAirport: true,
    airportCode: 'GZP',
    isHotel: false,
    services: ['24/7 teslimat', 'Ekspres check-in', 'Otopark teslimi'],
    isActive: true,
  },
  {
    id: 'office-ayt',
    name: 'Antalya Airport',
    code: 'AYT',
    address: 'Antalya Havalimanı 2. Dış Hatlar Terminali Karşılama Alanı',
    city: 'Antalya',
    district: 'Muratpaşa',
    postalCode: '07230',
    phone: '+90 242 555 10 02',
    email: 'ayt@ayracar.com',
    coordinates: { latitude: 36.8987, longitude: 30.8005 },
    openingHours,
    type: 'airport',
    isAirport: true,
    airportCode: 'AYT',
    isHotel: false,
    services: ['Valeli teslimat', 'Gece teslimi', 'Transfer desteği'],
    isActive: true,
  },
  {
    id: 'office-alanya-center',
    name: 'Alanya Center',
    code: 'ALA',
    address: 'Saray Mah. Atatürk Cad. No: 128',
    city: 'Antalya',
    district: 'Alanya',
    postalCode: '07400',
    phone: '+90 242 555 10 03',
    email: 'alanya@ayracar.com',
    coordinates: { latitude: 36.5441, longitude: 31.9954 },
    openingHours,
    type: 'office',
    isAirport: false,
    isHotel: false,
    services: ['Şehir içi teslimat', 'Araç değişimi', 'Uzun dönem kiralama'],
    isActive: true,
  },
  {
    id: 'office-mahmutlar',
    name: 'Mahmutlar Delivery Point',
    code: 'MHM',
    address: 'Barbaros Cd. No: 44',
    city: 'Antalya',
    district: 'Mahmutlar',
    postalCode: '07460',
    phone: '+90 242 555 10 04',
    email: 'mahmutlar@ayracar.com',
    coordinates: { latitude: 36.4948, longitude: 32.0902 },
    openingHours,
    type: 'office',
    isAirport: false,
    isHotel: false,
    services: ['Otel teslimatı', 'Site teslimatı'],
    isActive: true,
  },
  {
    id: 'office-konakli',
    name: 'Konaklı Resort Desk',
    code: 'KNK',
    address: 'İskele Cd. No: 9',
    city: 'Antalya',
    district: 'Konaklı',
    postalCode: '07491',
    phone: '+90 242 555 10 05',
    email: 'konakli@ayracar.com',
    coordinates: { latitude: 36.5863, longitude: 31.8551 },
    openingHours,
    type: 'hotel',
    isAirport: false,
    isHotel: true,
    hotelName: 'Konaklı Resort Hub',
    services: ['Resort içi teslimat', 'Hızlı iade'],
    isActive: false,
  },
];

export const mockVehicleGroups: AdminVehicleGroup[] = [
  {
    id: 'group-economy',
    name: 'Ekonomi',
    description: 'Şehir içi ve kısa tatil kullanımına uygun yakıt dostu araçlar.',
    imageUrl: '/assets/images/admin/group-economy.webp',
    vehicles: [],
    priceRange: { min: 34, max: 52 },
    depositAmount: 250,
    minAge: 21,
    minLicenseYears: 1,
    features: ['Klima', 'Bluetooth', 'Düşük yakıt tüketimi'],
    createdAt: '2026-01-04T09:00:00.000Z',
    updatedAt: '2026-03-14T10:30:00.000Z',
  },
  {
    id: 'group-comfort',
    name: 'Konfor',
    description: 'Aileler ve uzun yolcular için ekstra bagaj ve konfor alanı sunar.',
    imageUrl: '/assets/images/admin/group-comfort.webp',
    vehicles: [],
    priceRange: { min: 56, max: 78 },
    depositAmount: 350,
    minAge: 23,
    minLicenseYears: 2,
    features: ['Otomatik vites', 'Geniş bagaj', 'Geri görüş kamerası'],
    createdAt: '2026-01-06T08:30:00.000Z',
    updatedAt: '2026-03-18T15:00:00.000Z',
  },
  {
    id: 'group-suv',
    name: 'SUV',
    description: 'Yüksek sürüş pozisyonu ve geniş kabin arayan misafirler için.',
    imageUrl: '/assets/images/admin/group-suv.webp',
    vehicles: [],
    priceRange: { min: 75, max: 105 },
    depositAmount: 450,
    minAge: 25,
    minLicenseYears: 3,
    features: ['Otomatik vites', 'Yüksek oturma', 'Navigasyon'],
    createdAt: '2026-01-08T11:20:00.000Z',
    updatedAt: '2026-04-02T12:45:00.000Z',
  },
  {
    id: 'group-premium',
    name: 'Premium',
    description: 'İş seyahatleri ve VIP transferler için premium sedan araçlar.',
    imageUrl: '/assets/images/admin/group-premium.webp',
    vehicles: [],
    priceRange: { min: 118, max: 165 },
    depositAmount: 700,
    minAge: 27,
    minLicenseYears: 4,
    features: ['Deri koltuk', 'Adaptif hız sabitleme', 'Premium ses sistemi'],
    createdAt: '2026-01-12T10:10:00.000Z',
    updatedAt: '2026-04-05T09:10:00.000Z',
  },
  {
    id: 'group-hybrid',
    name: 'Hybrid',
    description: 'Düşük emisyon ve sessiz sürüş için hibrit seçenekler.',
    imageUrl: '/assets/images/admin/group-hybrid.webp',
    vehicles: [],
    priceRange: { min: 82, max: 122 },
    depositAmount: 500,
    minAge: 25,
    minLicenseYears: 3,
    features: ['Hibrit', 'Otomatik', 'Düşük tüketim'],
    createdAt: '2026-01-18T13:25:00.000Z',
    updatedAt: '2026-04-10T14:20:00.000Z',
  },
];

const createPriceBreakdown = (basePrice: number, rentalDays: number, extras: ReservationExtra[] = []): PriceBreakdown => {
  const extrasTotal = extras.reduce((sum, item) => sum + item.totalPrice, 0);
  const subtotal = basePrice + extrasTotal;
  const taxAmount = Number((subtotal * 0.2).toFixed(2));

  return {
    basePrice,
    rentalDays,
    extraFees: [
      { name: 'Teslim hizmeti', description: 'Ofis dışı teslimat', amount: 15, isOptional: true },
    ],
    extrasTotal,
    insuranceTotal: 0,
    subtotal,
    taxRate: 0.2,
    taxAmount,
    discountAmount: 0,
    totalAmount: subtotal + taxAmount,
    currency: 'EUR',
    depositAmount: 300,
  };
};

export const mockVehicles: AdminVehicle[] = [
  {
    id: 'vehicle-egea-34aya101',
    name: 'Fiat Egea 1.4 Easy',
    description: 'Alanya şehir içi kullanımı için ideal, düşük yakıt tüketimli sedan.',
    imageUrl: '/assets/images/admin/fiat-egea.webp',
    images: ['/assets/images/admin/fiat-egea.webp'],
    plate: '34 AYA 101',
    groupId: 'group-economy',
    officeId: 'office-alanya-center',
    groupName: 'Ekonomi',
    office: { id: 'office-alanya-center', name: 'Alanya Center' },
    group: { id: 'group-economy', name: 'Ekonomi' },
    transmission: TransmissionType.MANUAL,
    fuelType: FuelType.PETROL,
    seatCount: 5,
    luggageCapacity: 3,
    hasAirConditioning: true,
    minDriverAge: 21,
    minLicenseYears: 1,
    dailyPrice: 36,
    weeklyPrice: 224,
    monthlyPrice: 860,
    features: [vehicleFeatures.ac, vehicleFeatures.bluetooth],
    insuranceIncluded: true,
    mileageLimit: 250,
    extraMileagePrice: 0.35,
    availableExtras: vehicleExtras,
    status: 'Available',
    officeName: 'Alanya Center',
    adminNotes: 'Nisan sonunda iç temizlik planlandı.',
    lastMaintenanceDate: '2026-02-10T08:00:00.000Z',
    nextMaintenanceDate: '2026-05-10T08:00:00.000Z',
    mileage: 24150,
  },
  {
    id: 'vehicle-clio-07ayr202',
    name: 'Renault Clio Touch',
    description: 'Havalimanı teslimleri için çevik ve ekonomik hatchback.',
    imageUrl: '/assets/images/admin/renault-clio.webp',
    images: ['/assets/images/admin/renault-clio.webp'],
    plate: '07 AYR 202',
    groupId: 'group-economy',
    officeId: 'office-gzp',
    groupName: 'Ekonomi',
    office: { id: 'office-gzp', name: 'Gazipaşa Airport' },
    group: { id: 'group-economy', name: 'Ekonomi' },
    transmission: TransmissionType.AUTOMATIC,
    fuelType: FuelType.PETROL,
    seatCount: 5,
    luggageCapacity: 2,
    hasAirConditioning: true,
    minDriverAge: 21,
    minLicenseYears: 1,
    dailyPrice: 39,
    weeklyPrice: 246,
    monthlyPrice: 910,
    features: [vehicleFeatures.ac, vehicleFeatures.auto, vehicleFeatures.bluetooth],
    insuranceIncluded: true,
    mileageLimit: 250,
    extraMileagePrice: 0.35,
    availableExtras: vehicleExtras,
    status: 'Available',
    officeName: 'Gazipaşa Airport',
    adminNotes: 'Havalimanı karşılama filosunda aktif.',
    lastMaintenanceDate: '2026-03-02T09:00:00.000Z',
    nextMaintenanceDate: '2026-06-02T09:00:00.000Z',
    mileage: 18640,
  },
  {
    id: 'vehicle-corolla-07ayr303',
    name: 'Toyota Corolla Hybrid Flame',
    description: 'Uzun mesafe transferlerde sessiz ve verimli hibrit sürüş sunar.',
    imageUrl: '/assets/images/admin/toyota-corolla-hybrid.webp',
    images: ['/assets/images/admin/toyota-corolla-hybrid.webp'],
    plate: '07 AYR 303',
    groupId: 'group-hybrid',
    officeId: 'office-ayt',
    groupName: 'Hybrid',
    office: { id: 'office-ayt', name: 'Antalya Airport' },
    group: { id: 'group-hybrid', name: 'Hybrid' },
    transmission: TransmissionType.AUTOMATIC,
    fuelType: FuelType.HYBRID,
    seatCount: 5,
    luggageCapacity: 3,
    hasAirConditioning: true,
    minDriverAge: 25,
    minLicenseYears: 3,
    dailyPrice: 92,
    weeklyPrice: 610,
    monthlyPrice: 2260,
    features: [vehicleFeatures.ac, vehicleFeatures.auto, vehicleFeatures.hybrid, vehicleFeatures.nav],
    insuranceIncluded: true,
    mileageLimit: 300,
    extraMileagePrice: 0.4,
    availableExtras: vehicleExtras,
    status: 'Maintenance',
    officeName: 'Antalya Airport',
    adminNotes: 'Hibrit batarya kontrolü bekleniyor.',
    lastMaintenanceDate: '2026-04-08T07:30:00.000Z',
    nextMaintenanceDate: '2026-04-29T07:30:00.000Z',
    mileage: 32890,
  },
  {
    id: 'vehicle-qashqai-07ayr404',
    name: 'Nissan Qashqai Sky Pack',
    description: 'Aile tatilleri için geniş iç hacimli SUV.',
    imageUrl: '/assets/images/admin/nissan-qashqai.webp',
    images: ['/assets/images/admin/nissan-qashqai.webp'],
    plate: '07 AYR 404',
    groupId: 'group-suv',
    officeId: 'office-mahmutlar',
    groupName: 'SUV',
    office: { id: 'office-mahmutlar', name: 'Mahmutlar Delivery Point' },
    group: { id: 'group-suv', name: 'SUV' },
    transmission: TransmissionType.AUTOMATIC,
    fuelType: FuelType.DIESEL,
    seatCount: 5,
    luggageCapacity: 4,
    hasAirConditioning: true,
    minDriverAge: 25,
    minLicenseYears: 3,
    dailyPrice: 84,
    weeklyPrice: 560,
    monthlyPrice: 2080,
    features: [vehicleFeatures.ac, vehicleFeatures.auto, vehicleFeatures.nav, vehicleFeatures.camera],
    insuranceIncluded: true,
    mileageLimit: 300,
    extraMileagePrice: 0.45,
    availableExtras: vehicleExtras,
    status: 'Available',
    officeName: 'Mahmutlar Delivery Point',
    adminNotes: 'Yeni lastik seti takıldı.',
    lastMaintenanceDate: '2026-01-22T10:00:00.000Z',
    nextMaintenanceDate: '2026-05-22T10:00:00.000Z',
    mileage: 41730,
  },
  {
    id: 'vehicle-bmw3-34vip777',
    name: 'BMW 3 Series M Sport',
    description: 'VIP transfer ve üst segment iş seyahatleri için premium sedan.',
    imageUrl: '/assets/images/admin/bmw-3-series.webp',
    images: ['/assets/images/admin/bmw-3-series.webp'],
    plate: '34 VIP 777',
    groupId: 'group-premium',
    officeId: 'office-alanya-center',
    groupName: 'Premium',
    office: { id: 'office-alanya-center', name: 'Alanya Center' },
    group: { id: 'group-premium', name: 'Premium' },
    transmission: TransmissionType.AUTOMATIC,
    fuelType: FuelType.PETROL,
    seatCount: 5,
    luggageCapacity: 3,
    hasAirConditioning: true,
    minDriverAge: 27,
    minLicenseYears: 4,
    dailyPrice: 144,
    weeklyPrice: 980,
    monthlyPrice: 3590,
    features: [vehicleFeatures.ac, vehicleFeatures.auto, vehicleFeatures.nav, vehicleFeatures.camera],
    insuranceIncluded: true,
    mileageLimit: 350,
    extraMileagePrice: 0.7,
    availableExtras: vehicleExtras,
    status: 'Retired',
    officeName: 'Alanya Center',
    adminNotes: 'Filo satış listesine aktarıldı.',
    lastMaintenanceDate: '2026-01-11T11:00:00.000Z',
    nextMaintenanceDate: '2026-04-11T11:00:00.000Z',
    mileage: 96810,
  },
  {
    id: 'vehicle-duster-07ayr505',
    name: 'Dacia Duster Journey',
    description: 'Dağ yolları ve kırsal rotalar için dayanıklı SUV.',
    imageUrl: '/assets/images/admin/dacia-duster.webp',
    images: ['/assets/images/admin/dacia-duster.webp'],
    plate: '07 AYR 505',
    groupId: 'group-suv',
    officeId: 'office-gzp',
    groupName: 'SUV',
    office: { id: 'office-gzp', name: 'Gazipaşa Airport' },
    group: { id: 'group-suv', name: 'SUV' },
    transmission: TransmissionType.MANUAL,
    fuelType: FuelType.DIESEL,
    seatCount: 5,
    luggageCapacity: 4,
    hasAirConditioning: true,
    minDriverAge: 24,
    minLicenseYears: 2,
    dailyPrice: 78,
    weeklyPrice: 514,
    monthlyPrice: 1960,
    features: [vehicleFeatures.ac, vehicleFeatures.bluetooth, vehicleFeatures.nav],
    insuranceIncluded: true,
    mileageLimit: 300,
    extraMileagePrice: 0.45,
    availableExtras: vehicleExtras,
    status: 'Available',
    officeName: 'Gazipaşa Airport',
    adminNotes: 'Yüksek sezon transferleri için ayrıldı.',
    lastMaintenanceDate: '2026-02-18T08:15:00.000Z',
    nextMaintenanceDate: '2026-05-18T08:15:00.000Z',
    mileage: 38220,
  },
];

mockVehicleGroups.forEach((group) => {
  group.vehicles = mockVehicles.filter((vehicle) => vehicle.groupId === group.id);
});

export const mockCustomers: AdminCustomer[] = [
  {
    id: 'customer-001',
    firstName: 'Emma',
    lastName: 'Schneider',
    name: 'Emma Schneider',
    email: 'emma.schneider@example.com',
    phone: '+49 151 555 1001',
    nationality: 'Germany',
    reservationCount: 4,
    totalSpent: 1280,
    createdAt: '2026-01-09T09:40:00.000Z',
  },
  {
    id: 'customer-002',
    firstName: 'Ahmet',
    lastName: 'Kaya',
    name: 'Ahmet Kaya',
    email: 'ahmet.kaya@example.com',
    phone: '+90 532 555 1002',
    nationality: 'Türkiye',
    reservationCount: 2,
    totalSpent: 540,
    createdAt: '2026-02-13T10:20:00.000Z',
  },
  {
    id: 'customer-003',
    firstName: 'Olivia',
    lastName: 'Brown',
    name: 'Olivia Brown',
    email: 'olivia.brown@example.com',
    phone: '+44 7700 900003',
    nationality: 'United Kingdom',
    reservationCount: 5,
    totalSpent: 2195,
    createdAt: '2026-01-17T14:05:00.000Z',
  },
  {
    id: 'customer-004',
    firstName: 'Mehmet',
    lastName: 'Yıldız',
    name: 'Mehmet Yıldız',
    email: 'mehmet.yildiz@example.com',
    phone: '+90 533 555 1004',
    nationality: 'Türkiye',
    reservationCount: 1,
    totalSpent: 184,
    createdAt: '2026-03-07T11:55:00.000Z',
  },
  {
    id: 'customer-005',
    firstName: 'Sofia',
    lastName: 'Rossi',
    name: 'Sofia Rossi',
    email: 'sofia.rossi@example.com',
    phone: '+39 347 555 1005',
    nationality: 'Italy',
    reservationCount: 3,
    totalSpent: 910,
    createdAt: '2026-02-24T08:35:00.000Z',
  },
];

export const mockAdminUsers: AdminUser[] = [
  {
    id: 'admin-001',
    email: 'deniz.arslan@ayracar.com',
    fullName: 'Deniz Arslan',
    role: 'SuperAdmin',
    isActive: true,
    lastLoginAt: '2026-04-22T18:40:00.000Z',
    createdAt: '2026-01-02T08:00:00.000Z',
  },
  {
    id: 'admin-002',
    email: 'ayse.kurt@ayracar.com',
    fullName: 'Ayşe Kurt',
    role: 'Admin',
    isActive: true,
    lastLoginAt: '2026-04-23T07:15:00.000Z',
    createdAt: '2026-01-05T09:30:00.000Z',
  },
  {
    id: 'admin-003',
    email: 'murat.oz@ayracar.com',
    fullName: 'Murat Öz',
    role: 'Admin',
    isActive: true,
    lastLoginAt: '2026-04-22T20:05:00.000Z',
    createdAt: '2026-01-08T10:10:00.000Z',
  },
  {
    id: 'admin-004',
    email: 'selin.gunes@ayracar.com',
    fullName: 'Selin Güneş',
    role: 'Admin',
    isActive: false,
    lastLoginAt: '2026-03-29T16:45:00.000Z',
    createdAt: '2026-02-01T12:00:00.000Z',
  },
  {
    id: 'admin-005',
    email: 'kerem.tuna@ayracar.com',
    fullName: 'Kerem Tuna',
    role: 'Admin',
    isActive: true,
    lastLoginAt: null,
    createdAt: '2026-04-12T09:05:00.000Z',
  },
];

export const mockReservations: AdminReservation[] = [
  {
    id: 'reservation-001',
    publicCode: 'AYR-260401',
    reservationCode: 'AYR-260401',
    status: ReservationStatus.CONFIRMED,
    vehicleId: 'vehicle-clio-07ayr202',
    vehicleName: 'Renault Clio Touch',
    vehicleImage: '/assets/images/admin/renault-clio.webp',
    vehiclePlate: '07 AYR 202',
    assignedVehicleId: 'vehicle-clio-07ayr202',
    pickupOfficeId: 'office-gzp',
    pickupOfficeName: 'Gazipaşa Airport',
    pickupDate: '2026-05-02',
    pickupTime: '10:30',
    returnOfficeId: 'office-alanya-center',
    returnOfficeName: 'Alanya Center',
    returnDate: '2026-05-07',
    returnTime: '11:00',
    customer: mockCustomers[0],
    customerName: 'Emma Schneider',
    totalPrice: 384,
    vehicle: { id: 'vehicle-clio-07ayr202', name: 'Renault Clio Touch', plate: '07 AYR 202' },
    driver: {
      firstName: 'Emma',
      lastName: 'Schneider',
      dateOfBirth: '1992-03-14',
      licenseNumber: 'DE-4432118',
      licenseCountry: 'Germany',
      licenseIssueDate: '2012-05-01',
      licenseExpiryDate: '2032-05-01',
      isPrimaryDriver: true,
    },
    extras: [{ extraId: 'extra-full-insurance', name: 'Tam Kasko', quantity: 1, dailyPrice: 25, totalPrice: 125 }],
    priceBreakdown: createPriceBreakdown(195, 5, [{ extraId: 'extra-full-insurance', name: 'Tam Kasko', quantity: 1, dailyPrice: 25, totalPrice: 125 }]),
    createdAt: '2026-04-14T09:22:00.000Z',
    updatedAt: '2026-04-14T09:22:00.000Z',
    paymentStatus: PaymentStatus.CAPTURED,
    adminNotes: 'Müşteri VIP karşılama talep etti.',
  },
  {
    id: 'reservation-002',
    publicCode: 'AYR-260402',
    reservationCode: 'AYR-260402',
    status: ReservationStatus.ACTIVE,
    vehicleId: 'vehicle-qashqai-07ayr404',
    vehicleName: 'Nissan Qashqai Sky Pack',
    vehicleImage: '/assets/images/admin/nissan-qashqai.webp',
    vehiclePlate: '07 AYR 404',
    assignedVehicleId: 'vehicle-qashqai-07ayr404',
    pickupOfficeId: 'office-alanya-center',
    pickupOfficeName: 'Alanya Center',
    pickupDate: '2026-04-20',
    pickupTime: '14:00',
    returnOfficeId: 'office-mahmutlar',
    returnOfficeName: 'Mahmutlar Delivery Point',
    returnDate: '2026-04-26',
    returnTime: '10:00',
    customer: mockCustomers[1],
    customerName: 'Ahmet Kaya',
    totalPrice: 648,
    vehicle: { id: 'vehicle-qashqai-07ayr404', name: 'Nissan Qashqai Sky Pack', plate: '07 AYR 404' },
    driver: {
      firstName: 'Ahmet',
      lastName: 'Kaya',
      dateOfBirth: '1988-08-22',
      licenseNumber: 'TR-8845221',
      licenseCountry: 'Türkiye',
      licenseIssueDate: '2008-11-12',
      licenseExpiryDate: '2030-11-12',
      isPrimaryDriver: true,
    },
    extras: [{ extraId: 'extra-child-seat', name: 'Çocuk Koltuğu', quantity: 1, dailyPrice: 12, totalPrice: 72 }],
    priceBreakdown: createPriceBreakdown(468, 6, [{ extraId: 'extra-child-seat', name: 'Çocuk Koltuğu', quantity: 1, dailyPrice: 12, totalPrice: 72 }]),
    createdAt: '2026-04-02T13:05:00.000Z',
    updatedAt: '2026-04-20T14:04:00.000Z',
    paymentStatus: PaymentStatus.AUTHORIZED,
    checkedInAt: '2026-04-20T11:12:00.000Z',
    checkedInBy: 'Ayşe Kurt',
    adminNotes: 'Bebek koltuğu teslim edildi.',
  },
  {
    id: 'reservation-003',
    publicCode: 'AYR-260403',
    reservationCode: 'AYR-260403',
    status: ReservationStatus.CANCELLED,
    vehicleId: 'vehicle-corolla-07ayr303',
    vehicleName: 'Toyota Corolla Hybrid Flame',
    vehicleImage: '/assets/images/admin/toyota-corolla-hybrid.webp',
    pickupOfficeId: 'office-ayt',
    pickupOfficeName: 'Antalya Airport',
    pickupDate: '2026-04-12',
    pickupTime: '08:00',
    returnOfficeId: 'office-ayt',
    returnOfficeName: 'Antalya Airport',
    returnDate: '2026-04-17',
    returnTime: '08:00',
    customer: mockCustomers[2],
    customerName: 'Olivia Brown',
    totalPrice: 552,
    vehicle: { id: 'vehicle-corolla-07ayr303', name: 'Toyota Corolla Hybrid Flame' },
    driver: {
      firstName: 'Olivia',
      lastName: 'Brown',
      dateOfBirth: '1990-10-09',
      licenseNumber: 'UK-9981233',
      licenseCountry: 'United Kingdom',
      licenseIssueDate: '2010-10-21',
      licenseExpiryDate: '2030-10-21',
      isPrimaryDriver: true,
    },
    extras: [],
    priceBreakdown: createPriceBreakdown(460, 5),
    createdAt: '2026-03-28T18:05:00.000Z',
    updatedAt: '2026-04-01T07:30:00.000Z',
    paymentStatus: PaymentStatus.REFUNDED,
    cancellationReason: 'Uçuş iptal edildi.',
    refundAmount: 460,
    adminNotes: 'Tam iade onaylandı.',
  },
  {
    id: 'reservation-004',
    publicCode: 'AYR-260404',
    reservationCode: 'AYR-260404',
    status: ReservationStatus.COMPLETED,
    vehicleId: 'vehicle-egea-34aya101',
    vehicleName: 'Fiat Egea 1.4 Easy',
    vehicleImage: '/assets/images/admin/fiat-egea.webp',
    vehiclePlate: '34 AYA 101',
    assignedVehicleId: 'vehicle-egea-34aya101',
    pickupOfficeId: 'office-alanya-center',
    pickupOfficeName: 'Alanya Center',
    pickupDate: '2026-04-01',
    pickupTime: '09:30',
    returnOfficeId: 'office-alanya-center',
    returnOfficeName: 'Alanya Center',
    returnDate: '2026-04-04',
    returnTime: '09:30',
    customer: mockCustomers[3],
    customerName: 'Mehmet Yıldız',
    totalPrice: 147.6,
    vehicle: { id: 'vehicle-egea-34aya101', name: 'Fiat Egea 1.4 Easy', plate: '34 AYA 101' },
    driver: {
      firstName: 'Mehmet',
      lastName: 'Yıldız',
      dateOfBirth: '1996-07-01',
      licenseNumber: 'TR-6678902',
      licenseCountry: 'Türkiye',
      licenseIssueDate: '2016-07-15',
      licenseExpiryDate: '2028-07-15',
      isPrimaryDriver: true,
    },
    extras: [],
    priceBreakdown: createPriceBreakdown(108, 3),
    createdAt: '2026-03-22T12:15:00.000Z',
    updatedAt: '2026-04-04T09:42:00.000Z',
    paymentStatus: PaymentStatus.CAPTURED,
    checkedInAt: '2026-04-01T06:45:00.000Z',
    checkedOutAt: '2026-04-04T06:55:00.000Z',
    checkedInBy: 'Murat Öz',
    checkedOutBy: 'Murat Öz',
    adminNotes: 'Araç sorunsuz teslim edildi.',
  },
  {
    id: 'reservation-005',
    publicCode: 'AYR-260405',
    reservationCode: 'AYR-260405',
    status: ReservationStatus.PENDING,
    vehicleId: 'vehicle-duster-07ayr505',
    vehicleName: 'Dacia Duster Journey',
    vehicleImage: '/assets/images/admin/dacia-duster.webp',
    pickupOfficeId: 'office-gzp',
    pickupOfficeName: 'Gazipaşa Airport',
    pickupDate: '2026-05-10',
    pickupTime: '16:00',
    returnOfficeId: 'office-konakli',
    returnOfficeName: 'Konaklı Resort Desk',
    returnDate: '2026-05-16',
    returnTime: '12:00',
    customer: mockCustomers[4],
    customerName: 'Sofia Rossi',
    totalPrice: 626.4,
    vehicle: { id: 'vehicle-duster-07ayr505', name: 'Dacia Duster Journey' },
    driver: {
      firstName: 'Sofia',
      lastName: 'Rossi',
      dateOfBirth: '1991-11-19',
      licenseNumber: 'IT-4422881',
      licenseCountry: 'Italy',
      licenseIssueDate: '2011-03-17',
      licenseExpiryDate: '2031-03-17',
      isPrimaryDriver: true,
    },
    extras: [{ extraId: 'extra-wifi', name: 'Araç İçi Wi-Fi', quantity: 1, dailyPrice: 9, totalPrice: 54 }],
    priceBreakdown: createPriceBreakdown(468, 6, [{ extraId: 'extra-wifi', name: 'Araç İçi Wi-Fi', quantity: 1, dailyPrice: 9, totalPrice: 54 }]),
    createdAt: '2026-04-18T16:18:00.000Z',
    updatedAt: '2026-04-18T16:18:00.000Z',
    paymentStatus: PaymentStatus.PENDING,
    notes: 'Resort teslimatı talep edildi.',
  },
];

export const mockPricingRules: PricingRule[] = [
  {
    id: 'pricing-001',
    vehicleGroupId: 'group-economy',
    startDate: '2026-05-01',
    endDate: '2026-05-31',
    dailyPrice: 38,
    multiplier: 1.05,
    priority: 1,
    calculationType: 'fixed',
  },
  {
    id: 'pricing-002',
    vehicleGroupId: 'group-comfort',
    startDate: '2026-06-01',
    endDate: '2026-09-15',
    dailyPrice: 68,
    multiplier: 1.2,
    priority: 2,
    calculationType: 'multiplier',
    weekdayMultiplier: 1.1,
    weekendMultiplier: 1.25,
  },
  {
    id: 'pricing-003',
    vehicleGroupId: 'group-suv',
    startDate: '2026-07-01',
    endDate: '2026-08-31',
    dailyPrice: 86,
    multiplier: 1.18,
    priority: 3,
    calculationType: 'multiplier',
    weekdayMultiplier: 1.12,
    weekendMultiplier: 1.3,
  },
  {
    id: 'pricing-004',
    vehicleGroupId: 'group-premium',
    startDate: '2026-04-20',
    endDate: '2026-06-30',
    dailyPrice: 149,
    multiplier: 1,
    priority: 1,
    calculationType: 'fixed',
  },
  {
    id: 'pricing-005',
    vehicleGroupId: 'group-hybrid',
    startDate: '2026-05-15',
    endDate: '2026-10-15',
    dailyPrice: 96,
    multiplier: 1.1,
    priority: 2,
    calculationType: 'multiplier',
    weekdayMultiplier: 1.05,
    weekendMultiplier: 1.18,
  },
];

export const mockCampaigns: Campaign[] = [
  {
    id: 'campaign-001',
    code: 'EARLY26',
    name: 'Early Summer Booking',
    description: 'Mayıs ayı ön rezervasyonlarında %10 indirim.',
    discountType: 'PERCENTAGE',
    discountValue: 10,
    minRentalDays: 4,
    validFrom: '2026-04-01T00:00:00.000Z',
    validUntil: '2026-05-15T23:59:59.000Z',
    isActive: true,
  },
  {
    id: 'campaign-002',
    code: 'AIRPORT50',
    name: 'Airport Welcome',
    description: 'Havalimanı teslimlerinde 50 EUR sabit indirim.',
    discountType: 'FIXED_AMOUNT',
    discountValue: 50,
    maxDiscount: 50,
    startDate: '2026-04-10T00:00:00.000Z',
    endDate: '2026-06-30T23:59:59.000Z',
    validFrom: '2026-04-10T00:00:00.000Z',
    validUntil: '2026-06-30T23:59:59.000Z',
    isActive: true,
  },
  {
    id: 'campaign-003',
    code: 'LONGSTAY',
    name: 'Long Stay Bonus',
    description: '10 gün ve üzeri kiralamalarda ekstra %12 indirim.',
    discountType: 'PERCENTAGE',
    discountValue: 12,
    minRentalDays: 10,
    startDate: '2026-05-01T00:00:00.000Z',
    endDate: '2026-10-31T23:59:59.000Z',
    validFrom: '2026-05-01T00:00:00.000Z',
    validUntil: '2026-10-31T23:59:59.000Z',
    isActive: true,
  },
  {
    id: 'campaign-004',
    code: 'VIPPLUS',
    name: 'Premium Upgrade Week',
    description: 'Premium grupta 75 EUR sabit avantaj.',
    discountType: 'FIXED_AMOUNT',
    discountValue: 75,
    maxDiscount: 75,
    startDate: '2026-07-05T00:00:00.000Z',
    endDate: '2026-07-20T23:59:59.000Z',
    validFrom: '2026-07-05T00:00:00.000Z',
    validUntil: '2026-07-20T23:59:59.000Z',
    isActive: false,
  },
  {
    id: 'campaign-005',
    code: 'RESORT26',
    name: 'Resort Delivery Benefit',
    description: 'Konaklı ve Mahmutlar teslimlerinde %8 indirim.',
    discountType: 'PERCENTAGE',
    discountValue: 8,
    minRentalDays: 3,
    startDate: '2026-06-01T00:00:00.000Z',
    endDate: '2026-09-30T23:59:59.000Z',
    validFrom: '2026-06-01T00:00:00.000Z',
    validUntil: '2026-09-30T23:59:59.000Z',
    isActive: true,
  },
];

export const mockFeatureFlags: FeatureFlag[] = [
  { id: 'flag-001', name: 'admin.reports.revenue', enabled: true, description: 'Gelir raporu ekranını gösterir.' },
  { id: 'flag-002', name: 'admin.reservations.manualRefund', enabled: true, description: 'Rezervasyon ekranında manuel iade akışını açar.' },
  { id: 'flag-003', name: 'admin.vehicles.maintenancePlanner', enabled: true, description: 'Araç bakım planlama modülünü etkinleştirir.' },
  { id: 'flag-004', name: 'admin.users.supervisorApproval', enabled: false, description: 'Admin kullanıcı aksiyonlarında ikinci onay ister.' },
  { id: 'flag-005', name: 'admin.pricing.dynamicPreview', enabled: true, description: 'Fiyat kuralı değişikliklerinde ön izleme gösterir.' },
];

export const mockAuditLogs: AuditLog[] = [
  {
    id: 'audit-001',
    action: 'vehicle.updated',
    entityType: 'vehicle',
    entityId: 'vehicle-corolla-07ayr303',
    userId: 'admin-002',
    userEmail: 'ayse.kurt@ayracar.com',
    timestamp: '2026-04-21T08:40:00.000Z',
    details: 'Toyota Corolla Hybrid için bakım tarihi güncellendi.',
  },
  {
    id: 'audit-002',
    action: 'reservation.cancelled',
    entityType: 'reservation',
    entityId: 'reservation-003',
    userId: 'admin-003',
    userEmail: 'murat.oz@ayracar.com',
    timestamp: '2026-04-01T07:31:00.000Z',
    details: 'Rezervasyon müşteri talebi ile iptal edildi ve iade işlendi.',
  },
  {
    id: 'audit-003',
    action: 'pricing-rule.created',
    entityType: 'pricingRule',
    entityId: 'pricing-005',
    userId: 'admin-001',
    userEmail: 'deniz.arslan@ayracar.com',
    timestamp: '2026-04-12T11:10:00.000Z',
    details: 'Hybrid yaz sezonu fiyat kuralı oluşturuldu.',
  },
  {
    id: 'audit-004',
    action: 'feature-flag.updated',
    entityType: 'featureFlag',
    entityId: 'flag-004',
    userId: 'admin-001',
    userEmail: 'deniz.arslan@ayracar.com',
    timestamp: '2026-04-15T15:20:00.000Z',
    details: 'Supervisor approval özelliği devre dışı bırakıldı.',
  },
  {
    id: 'audit-005',
    action: 'office.updated',
    entityType: 'office',
    entityId: 'office-konakli',
    userId: 'admin-002',
    userEmail: 'ayse.kurt@ayracar.com',
    timestamp: '2026-04-17T10:50:00.000Z',
    details: 'Konaklı desk geçici olarak pasif duruma alındı.',
  },
];

export const mockReportStats: ReportStat[] = [
  { label: 'Toplam Gelir', value: 48210, change: 12.4, changeType: 'increase' },
  { label: 'Aktif Rezervasyon', value: 38, change: 4.1, changeType: 'increase' },
  { label: 'Filo Doluluk', value: '71%', change: -2.3, changeType: 'decrease' },
  { label: 'Ortalama Sipariş', value: 312, change: 1.8, changeType: 'increase' },
  { label: 'İptal Oranı', value: '4.8%', change: 0, changeType: 'neutral' },
];

export const mockRevenueReports: RevenueReport[] = [
  {
    period: '2026-04',
    totalRevenue: 48210,
    totalReservations: 154,
    averageOrderValue: 313.05,
    dailyBreakdown: [
      { date: '2026-04-19', revenue: 1420, reservations: 5 },
      { date: '2026-04-20', revenue: 1585, reservations: 6 },
      { date: '2026-04-21', revenue: 1675, reservations: 6 },
      { date: '2026-04-22', revenue: 1490, reservations: 5 },
      { date: '2026-04-23', revenue: 1760, reservations: 7 },
    ],
  },
  {
    period: '2026-Q2',
    totalRevenue: 126430,
    totalReservations: 398,
    averageOrderValue: 317.66,
    dailyBreakdown: [
      { date: '2026-04-01', revenue: 1290, reservations: 4 },
      { date: '2026-05-01', revenue: 1840, reservations: 7 },
      { date: '2026-06-01', revenue: 2210, reservations: 8 },
    ],
  },
];

export const mockOccupancyReports: OccupancyReport[] = [
  {
    period: '2026-04',
    totalVehicles: 62,
    occupiedVehicles: 44,
    occupancyRate: 70.97,
    dailyBreakdown: [
      { date: '2026-04-19', occupiedVehicles: 42, totalVehicles: 62, occupancyRate: 67.74 },
      { date: '2026-04-20', occupiedVehicles: 45, totalVehicles: 62, occupancyRate: 72.58 },
      { date: '2026-04-21', occupiedVehicles: 46, totalVehicles: 62, occupancyRate: 74.19 },
      { date: '2026-04-22', occupiedVehicles: 43, totalVehicles: 62, occupancyRate: 69.35 },
      { date: '2026-04-23', occupiedVehicles: 44, totalVehicles: 62, occupancyRate: 70.97 },
    ],
  },
  {
    period: '2026-Q2',
    totalVehicles: 62,
    occupiedVehicles: 41,
    occupancyRate: 66.13,
    dailyBreakdown: [
      { date: '2026-04-01', occupiedVehicles: 39, totalVehicles: 62, occupancyRate: 62.9 },
      { date: '2026-05-01', occupiedVehicles: 41, totalVehicles: 62, occupancyRate: 66.13 },
      { date: '2026-06-01', occupiedVehicles: 48, totalVehicles: 62, occupancyRate: 77.42 },
    ],
  },
];

export const mockPopularVehicles: PopularVehicleReportItem[] = [
  { vehicleName: 'Renault Clio Touch', rentalCount: 28, revenue: 8220 },
  { vehicleName: 'Fiat Egea 1.4 Easy', rentalCount: 24, revenue: 6480 },
  { vehicleName: 'Nissan Qashqai Sky Pack', rentalCount: 19, revenue: 9120 },
  { vehicleName: 'Toyota Corolla Hybrid Flame', rentalCount: 16, revenue: 10140 },
  { vehicleName: 'Dacia Duster Journey', rentalCount: 14, revenue: 7340 },
];
