namespace RentACar.API.Contracts.Fleet;

public sealed record PublicVehicleDto(
    Guid Id,
    string Brand,
    string Model,
    int Year,
    string Color,
    Guid? GroupId,
    string GroupName,
    string GroupNameEn,
    Guid OfficeId,
    string Status,
    string? PhotoUrl,
    decimal? DailyPrice,
    decimal DepositAmount,
    int MinAge,
    int MinLicenseYears,
    IReadOnlyList<string> Features,
    string? Transmission = null,
    string? FuelType = null,
    int? SeatCount = null,
    int? LuggageCapacity = null,
    string? BodyType = null,
    int? DoorCount = null,
    string? Engine = null,
    int? PowerHp = null,
    string[]? PhotoUrls = null);
