const copy = {
  "tr": {
    "title": "Rezervasyon yönetimi",
    "previousFees": "Önceden kabul edilen değişiklik ücretleri",
    "status": "Durum", "Confirmed": "Onaylandı", "Cancelled": "İptal edildi", "Active": "Aktif", "Completed": "Tamamlandı",
    "reference": "Rezervasyon kodu",
    "email": "E-posta",
    "sendCode": "Doğrulama kodu gönder",
    "sent": "Bilgiler eşleşiyorsa e-postanıza 10 dakika geçerli bir kod gönderildi.",
    "code": "Doğrulama kodu",
    "verify": "Doğrula",
    "logout": "Oturumu kapat",
    "cancel": "Rezervasyonu iptal et",
    "changeDates": "Tarihleri değiştir",
    "pickup": "Teslim tarihi ve saati",
    "returnDate": "İade tarihi ve saati",
    "quote": "Yeni fiyatı hesapla",
    "accept": "Yeni toplamı ve koşulları kabul et",
    "fee": "İşlem ücreti",
    "total": "Toplam",
    "difference": "Fiyat farkı",
    "unavailable": "Bu rezervasyon için işlem koşulları tanımlı değil veya işlem süresi geçti.",
    "error": "İşlem tamamlanamadı. Bilgileri ve güncel koşulları kontrol edip tekrar deneyin.",
    "expired": "Erişim geçersiz veya süresi doldu. Yeniden doğrulayın.",
    "required": "Bu alanı geçerli şekilde doldurun.",
    "ageAtPickup": "Teslim tarihinde yaşınız",
    "licenseYearsAtPickup": "Teslim tarihinde tamamlanan ehliyet yılı",
    "licenseValidThroughReturn": "Ehliyetim kiralama sonuna kadar geçerli olacak.",
    "documentsAvailableAtPickup": "Teslimde geçerli kimlik ve ehliyet belgelerimi göstereceğim.",
    "confirmCancel": "Gösterilen iptal ücretini kabul ediyor ve iptali onaylıyorum.",
    "updated": "Rezervasyon güncellendi.",
    "loading": "İşleniyor…",
    "timeZone": "Saatler Türkiye saatidir.",
    "manage": "Rezervasyonumu yönet",
    "expires": "Teklifin son geçerlilik zamanı"
  },
  "en": {
    "title": "Manage reservation",
    "previousFees": "Previously accepted change fees",
    "status": "Status", "Confirmed": "Confirmed", "Cancelled": "Cancelled", "Active": "Active", "Completed": "Completed",
    "reference": "Reservation code",
    "email": "Email",
    "sendCode": "Send verification code",
    "sent": "If the details match, a code valid for 10 minutes has been sent to your email.",
    "code": "Verification code",
    "verify": "Verify",
    "logout": "Sign out",
    "cancel": "Cancel reservation",
    "changeDates": "Change dates",
    "pickup": "Pickup date and time",
    "returnDate": "Return date and time",
    "quote": "Calculate new price",
    "accept": "Accept new total and conditions",
    "fee": "Service fee",
    "total": "Total",
    "difference": "Price difference",
    "unavailable": "Conditions are not configured for this reservation or the deadline has passed.",
    "error": "The operation could not be completed. Check the details and current conditions and retry.",
    "expired": "Access is invalid or expired. Verify again.",
    "required": "Enter a valid value.",
    "ageAtPickup": "Age on pickup date",
    "licenseYearsAtPickup": "Completed licence years at pickup",
    "licenseValidThroughReturn": "My licence will remain valid through the rental.",
    "documentsAvailableAtPickup": "I will present valid identity and driving licence documents at pickup.",
    "confirmCancel": "I accept the displayed cancellation fee and confirm cancellation.",
    "updated": "Reservation updated.",
    "loading": "Processing…",
    "timeZone": "All times are Turkey time.",
    "manage": "Manage my reservation",
    "expires": "Offer expires"
  },
  "de": {
    "title": "Reservierung verwalten",
    "previousFees": "Zuvor akzeptierte Änderungsgebühren",
    "status": "Status", "Confirmed": "Bestätigt", "Cancelled": "Storniert", "Active": "Aktiv", "Completed": "Abgeschlossen",
    "reference": "Reservierungscode",
    "email": "E-Mail",
    "sendCode": "Bestätigungscode senden",
    "sent": "Wenn die Angaben übereinstimmen, wurde ein 10 Minuten gültiger Code per E-Mail gesendet.",
    "code": "Bestätigungscode",
    "verify": "Bestätigen",
    "logout": "Abmelden",
    "cancel": "Reservierung stornieren",
    "changeDates": "Daten ändern",
    "pickup": "Abholdatum und Uhrzeit",
    "returnDate": "Rückgabedatum und Uhrzeit",
    "quote": "Neuen Preis berechnen",
    "accept": "Neuen Gesamtpreis und Bedingungen akzeptieren",
    "fee": "Bearbeitungsgebühr",
    "total": "Gesamt",
    "difference": "Preisdifferenz",
    "unavailable": "Bedingungen sind nicht festgelegt oder die Frist ist abgelaufen.",
    "error": "Vorgang fehlgeschlagen. Prüfen Sie Angaben und aktuelle Bedingungen und versuchen Sie es erneut.",
    "expired": "Zugriff ungültig oder abgelaufen. Bitte erneut bestätigen.",
    "required": "Gültigen Wert eingeben.",
    "ageAtPickup": "Alter bei Abholung",
    "licenseYearsAtPickup": "Volle Führerscheinjahre bei Abholung",
    "licenseValidThroughReturn": "Mein Führerschein bleibt bis Mietende gültig.",
    "documentsAvailableAtPickup": "Ich lege bei Abholung gültige Ausweis- und Führerscheindokumente vor.",
    "confirmCancel": "Ich akzeptiere die angezeigte Stornogebühr und bestätige die Stornierung.",
    "updated": "Reservierung aktualisiert.",
    "loading": "Wird bearbeitet…",
    "timeZone": "Alle Zeiten gelten für die Türkei.",
    "manage": "Meine Reservierung verwalten",
    "expires": "Angebot gültig bis"
  },
  "ru": {
    "title": "Управление бронированием",
    "previousFees": "Ранее принятые сборы за изменения",
    "status": "Статус", "Confirmed": "Подтверждено", "Cancelled": "Отменено", "Active": "Активно", "Completed": "Завершено",
    "reference": "Код бронирования",
    "email": "Электронная почта",
    "sendCode": "Отправить код",
    "sent": "Если данные совпадают, на почту отправлен код, действующий 10 минут.",
    "code": "Код подтверждения",
    "verify": "Подтвердить",
    "logout": "Выйти",
    "cancel": "Отменить бронирование",
    "changeDates": "Изменить даты",
    "pickup": "Дата и время получения",
    "returnDate": "Дата и время возврата",
    "quote": "Рассчитать новую цену",
    "accept": "Принять новую сумму и условия",
    "fee": "Сбор за операцию",
    "total": "Итого",
    "difference": "Разница в цене",
    "unavailable": "Условия не настроены или срок выполнения операции истёк.",
    "error": "Не удалось выполнить операцию. Проверьте данные и актуальные условия и повторите попытку.",
    "expired": "Доступ недействителен или истёк. Пройдите проверку снова.",
    "required": "Введите корректное значение.",
    "ageAtPickup": "Возраст на дату получения",
    "licenseYearsAtPickup": "Полных лет водительского стажа при получении",
    "licenseValidThroughReturn": "Мои права будут действительны до конца аренды.",
    "documentsAvailableAtPickup": "При получении я предъявлю действительные документы и водительские права.",
    "confirmCancel": "Я принимаю указанный сбор и подтверждаю отмену.",
    "updated": "Бронирование обновлено.",
    "loading": "Обработка…",
    "timeZone": "Время указано по Турции.",
    "manage": "Управлять моим бронированием",
    "expires": "Предложение действительно до"
  },
  "ar": {
    "title": "إدارة الحجز",
    "previousFees": "رسوم التغيير المقبولة سابقًا",
    "status": "الحالة", "Confirmed": "مؤكد", "Cancelled": "ملغى", "Active": "نشط", "Completed": "مكتمل",
    "reference": "رمز الحجز",
    "email": "البريد الإلكتروني",
    "sendCode": "إرسال رمز التحقق",
    "sent": "إذا تطابقت البيانات، أُرسل رمز صالح لمدة 10 دقائق إلى بريدك.",
    "code": "رمز التحقق",
    "verify": "تحقق",
    "logout": "تسجيل الخروج",
    "cancel": "إلغاء الحجز",
    "changeDates": "تغيير التواريخ",
    "pickup": "تاريخ ووقت الاستلام",
    "returnDate": "تاريخ ووقت الإرجاع",
    "quote": "حساب السعر الجديد",
    "accept": "قبول المجموع والشروط الجديدة",
    "fee": "رسوم العملية",
    "total": "المجموع",
    "difference": "فرق السعر",
    "unavailable": "لم تُحدد الشروط لهذا الحجز أو انتهت المهلة.",
    "error": "تعذر إكمال العملية. تحقق من البيانات والشروط الحالية وحاول مجدداً.",
    "expired": "الدخول غير صالح أو منتهي. تحقق مرة أخرى.",
    "required": "أدخل قيمة صحيحة.",
    "ageAtPickup": "العمر عند الاستلام",
    "licenseYearsAtPickup": "سنوات الرخصة المكتملة عند الاستلام",
    "licenseValidThroughReturn": "ستظل رخصتي سارية حتى نهاية الإيجار.",
    "documentsAvailableAtPickup": "سأقدم وثائق هوية ورخصة قيادة سارية عند الاستلام.",
    "confirmCancel": "أقبل رسوم الإلغاء المعروضة وأؤكد الإلغاء.",
    "updated": "تم تحديث الحجز.",
    "loading": "جارٍ المعالجة…",
    "timeZone": "جميع الأوقات بتوقيت تركيا.",
    "manage": "إدارة حجزي",
    "expires": "ينتهي العرض"
  }
};

export function guestCopy(locale: string) { return copy[locale as keyof typeof copy] ?? copy.en; }
